### ISSUE TITLE
[Bug] Validation of cidrs in `VRFRouteConfiguration` is not accurate.

### ISSUE THREAD

**Issue by Cellebyte** [telekom/das-schiff-network-operator#154]
## Description

We implemented in the past a check which validates `VRFRouteconfiguration` to not have the same `.spec.import.cidr` twice inside a CR.

## Current Behaviour

It denies the configuration I apply as it should.

```log
network-system    	<kustomization-name>              	main@<ref>  	False    	False	VRFRouteConfiguration/vrf dry-run failed (Forbidden): admission webhook "vvrfrouteconfiguration.kb.io" denied the request: there are duplicated items in the VrfRouteConfiguration: [::/0]
```

## Expected Behaviour

The resource applies correctly as I have one general `permit: deny` and a more specific `permit: allow` later.

```yaml
apiVersion: network.schiff.telekom.de/v1alpha1
kind: VRFRouteConfiguration
metadata:
  name: internet
spec:
  vrf: internet
  seq: 4
  import:
    # only deny the default route
    - cidr: ::/0
      action: deny
    - cidr: 10.0.0.0/16
      action: permit
      le: 32
    - cidr: ::/0
      action: permit
      # estimated guess
      # range between /44 and /128 should be fine to learn
      ge: 44
      le: 128
  export: []

```

If you need further information just comment on the Issue.
