### ISSUE TITLE
How to create bridges

### ISSUE THREAD

**Issue by networkop** [telekom/das-schiff-network-operator#57]
👋 I'm trying to figure out how to use network operator to create a linux bridge and maybe plumb some interfaces into it.  Looking at `layer2networkconfiguration` I can't figure it out. Can anyone provide an example?

**Comment by Cellebyte** [comment]
Hey `Layer2NetworkConfiguration` should create a bridge, but it is currently heavily bound to a vtep so a VXLAN Overlay termination. It is currently mainly used for that. 

```yaml
apiVersion: network.schiff.telekom.de/v1alpha1
kind: Layer2NetworkConfiguration
metadata:
  name: vlan-100
spec:
  # this creates a separate interface for macvlan binding
  createMacVLANInterface: true
  # relevant only for der configuration
  advertiseNeighbors: false
  ## below options add a veth pair for gateway termination
  anycastGateways:
  - "10.0.0.1/24"
  anycastMac: "00:00:00:01:02:03"
  ##
  # required
  id: 100 # creates a bridge called vlan.100
  # required
  vni: 10100 # creates an vxlan endpoint called vx.10100
  mtu: 1500 # sets the correct mtu to all interfaces
```
